### ISSUE TITLE
New Guids ignore "Remove Dashes" checkbox

### ISSUE THREAD

**Issue by jamsidedown** [AlexHedley/Utility-Blazor#55]
On the [Guids](https://alexhedley.com/Utility-Blazor/guid) page, if I check the "Remove Dashes" checkbox the current Guid has its dashes removed, but if I leave the checkbox checked any subsequent Guid I generate still have dashes.

![Screenshot 2023-09-26 145833](https://github.com/AlexHedley/Utility-Blazor/assets/46314954/823432d7-4c55-4d77-bf43-ce0bc010c9c0)

![Screenshot 2023-09-26 145839](https://github.com/AlexHedley/Utility-Blazor/assets/46314954/f33504ae-8459-4fd9-8cf5-645e850eee0d)

**Comment by AlexHedley** [comment]
I was hoping nobody would notice yet :p
Need to fix the logic.
Think the “Add braces” is broken too depending on order of clicks.
