### ISSUE TITLE
Monaco Editor

### ISSUE THREAD

**Issue by AlexHedley** [AlexHedley/Utility-Blazor#6]
Blazor:

https://github.com/SteveSandersonMS/MonacoRazor

**Comment by alex-hedley** [comment]
[BlazorMonaco](https://github.com/serdarciplak/BlazorMonaco)

**Comment by alex-hedley** [comment]
Fluent UI Blazor components demo page
https://www.fluentui-blazor.net/Lab/MonacoEditor

Use Fluent UI Web Components with Blazor
https://learn.microsoft.com/en-us/fluent-ui/web-components/integrations/blazor
